#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
typedef void **va_list;

/* 2 */
struct __attribute__((aligned(4))) structQueue
{
  unsigned int nextAvailableSlot;
  char *dword4;
  _DWORD maxSize;
  _DWORD valuePtr;
  _DWORD valuePtrXOR;
};

/* 5 */
struct __attribute__((packed)) __attribute__((aligned(2))) struct_queue_big
{
  __int16 poistionRel;
  __int16 field_2;
  __int16 poistionRel_FromEnd;
  __int16 field_6;
  unsigned __int8 base;
  unsigned __int8 field_9;
  __int16 field_A;
  unsigned __int8 field_C;
  unsigned __int8 field_D;
  unsigned __int8 field_E;
  char field_F;
  __int16 poistionRel_xor;
  __int16 field_12;
  __int16 field_14;
  __int16 field_16;
  unsigned __int8 field_18;
  unsigned __int8 field_19;
  __int16 field_1A;
  unsigned __int8 field_1C;
  unsigned __int8 field_1D;
  unsigned __int8 field_1E;
  char field_1F;
};

/* 7 */
struct struct_error_ref
{
  _WORD word0;
  _WORD word2;
  _WORD word4;
  _WORD word6;
};

/* 8 */
struct __attribute__((aligned(4))) struct_bg
{
  int field_0;
  char field_4;
  char field_5;
  __int16 field_6;
  struct_bg *field_8;
  int field_C;
  __int16 field_10;
  __int16 field_12;
  int field_14;
  int field_18;
  int field_1C;
  int field_20;
  int field_24;
  int field_28;
};

/* 9 */
struct struct_usb_something24100
{
  _BYTE gap0[6];
  _BYTE byte6;
  _BYTE byte7;
  _BYTE gap8[19];
  _BYTE byte1B;
  _BYTE gap1C[2];
  _BYTE byte1E;
};

/* 19 */
struct struct_0
{
  void *anonymous_0;
  const char *aAboveGoal;
  const char *aAddBgReading;
  const char *aAlertsReminder;
  const char *aRef02d03d04d05;
  const char *aRef02d03d02d03;
  const char *aAllHistory;
  const char *aAlarmHistory_1;
  const char *aAlwaysOn;
  const char *aA_2;
  const char *aApril;
  const char *aAsAResultOfT_0;
  const char *aAsAResultOfThe;
  const char *aAsAResultOfT_2;
  const char *aAssignEditBgTa;
  const char *aAugust;
  const char *aAutoOff;
  const char *aAvgBg;
  const char *aAvgReadsDay;
  const char *aMeterTemperatu;
  const char *aTempStopped;
  const char *aMaxBasal;
  const char *aBasalB;
  const char *aBasalPrograms;
  const char *aTempBasalYRema;
  const char *aDeliveryInterr;
  const char *aOffBeepOnly;
  const char *aBelowGoal;
  const char *aBg;
  const char *aCheckForKetone;
  const char *aBgHistory;
  const char *aLastBg;
  const char *aTreatYourLowBg;
  const char *aBgReadingWasMa;
  const char *aMeterErrD;
  const char *aBgMeter;
  const char *aMinBgForCalcs;
  const char *aControl;
  const char *aPreMeal;
  const char *aPostMeal;
  const char *aMissedBolus;
  const char *aCarbGuess;
  const char *aBasalEvaluatio;
  const char *aBasalEvaluat_0;
  const char *aSkippedMeal;
  const char *aExerciseLight;
  const char *aExerciseModera;
  const char *aExerciseStrenu;
  const char *aFasting;
  const char *aSickDay;
  const char *aKetonesNeg;
  const char *aKetonesTrace;
  const char *aKetonesSmall;
  const char *aKetonesModerat;
  const char *aKetonesLarge;
  const char *aPreBedtime;
  const char *aTargetBg_0;
  const char *aNoteACorrectio;
  const char *aShortestTimeRe;
  const char *aBgReminder;
  const char *aBgTag;
  const char *aBgGoal;
  const char *aBolusCalcs;
  const char *aSuggestedBol_0;
  const char *aBolusStoppedPr;
  const char *aBolusHistory_0;
  const char *aBolusIncrement;
  const char *aMaxBolus;
  const char *aBolusB;
  const char *aBolusPresets;
  const char *aBolus_4;
  const char *aBolusBasalCalc;
  const char *aBolusStopped;
  const char *aBolusReminders;
  const char *aImmediateBolus;
  const char *anonymous_1;
  const char *aCalories;
  const char *aCancelExtended;
  const char *aCancelTempBasa;
  const char *aNoteForBolusCa;
  const char *aCarbHistory;
  const char *aCarbPresets;
  const char *aE_1;
  const char *aG_1;
  const char *aG_2;
  const char *anonymous_2;
  const char *anonymous_3;
  const char *aCarbPresetB;
  const char *aCarbsG;
  const char *aCarbs;
  const char *aExceedsMaxBolu;
  const char *aAdjustedForIob;
  const char *anonymous_4;
  const char *anonymous_5;
  const char *anonymous_6;
  const char *anonymous_7;
  const char *aChangePod;
  const char *aChangeSensor;
  const char *aChangeTransmit;
  const char *aEdit;
  const char *aChecking;
  const char *aCheckAlarms;
  const char *aLastStatus;
  const char *aBasal_0;
  const char *aBolus_3;
  const char *aPod;
  const char *aSettings;
  const char *aSuspendResume;
  const char *aConfidenceRemi;
  const char *aCopy;
  const char *aCorrectionU;
  const char *aMMM;
  const char *aBgB;
  const char *aCorrectionFact;
  const char *aCorrectionIob;
  const char *aCorrection;
  const char *aReverseCorre_0;
  const char *aCorrect;
  const char *aCorr_Above;
  const char *aCorruptRecord;
  const char *aCustomRemind_1;
  const char *aReminderB;
  const char *aCustomBgTags;
  const char *aCustomTagB;
  const char *aDaily;
  const char *aDailyBasal;
  const char *aDate;
  const char *aDate_1;
  const char *aDateTime;
  const char *aDays;
  const char *aPodDeactivated;
  const char *aDecember;
  const char *aDelete;
  const char *aDeliveringBolu;
  const char *aDiagnostics;
  const char *aBgUnits;
  const char *anonymous_8;
  const char *aEnterManually;
  const char *aExpiration;
  const char *aExt;
  const char *aE_0;
  const char *aExtended;
  const char *aExtendedBolusU;
  const char *aExtExtendedBol;
  const char *aFavorites;
  const char *aFat;
  const char *aFebruary;
  const char *aFiber;
  const char *a50U;
  const char *aFoodLibrary_0;
  const char *aMoreActions;
  const char *aGoal_1;
  const char *aG_0;
  const char *aGCarb;
  const char *aGCarbU;
  const char *aHigh;
  const char *aA_1;
  const char *aBdh;
  const char *aHr;
  const char *aIcRatio;
  const char *aIcRatio_1;
  const char *a1UPerIinsulinD;
  const char *anonymous_9;
  const char *aInsulinAction;
  const char *aInsulinSuspend;
  const char *aWithinGoal;
  const char *aIob;
  const char *aInsulinOnBoard;
  const char *aJanuary;
  const char *aJuly;
  const char *aJune;
  const char *aLastBolus;
  const char *aLastStatusDT;
  const char *aLessThan1G;
  const char *aBacklightTimeO;
  const char *aLow;
  const char *aLowReservoir;
  const char *aManageBgTagLis;
  const char *aManual;
  const char *aMarch;
  const char *aMax;
  const char *aMay;
  const char *aMeals;
  const char *aMeal;
  const char *aMealDD;
  const char *aMeal_1;
  const char *aMealIob;
  const char *aMgDl;
  const char *aMgDlPerU;
  const char *aMin;
  const char *aMinMax;
  const char *aMin_0;
  const char *aMissedBolusRem;
  const char *aMmolL;
  const char *aMmolLPerU;
  const char *aMyInfo_0;
  const char *aMyRecords;
  const char *aNewLabel;
  const char *aStatusNotAvail;
  const char *anonymous_10;
  const char *aNoon;
  const char *aNa;
  const char *aNoData;
  const char *aNovember;
  const char *aNow;
  const char *aOctober;
  const char *aOff;
  const char *aOff_0;
  const char *aOn;
  const char *aOneTimeOnly;
  const char *aOtherInformati;
  const char *aActionOccurred;
  const char *aRatiosFactorsT;
  const char *anonymous_11;
  const char *anonymous_12;
  const char *aPleaseWait;
  const char *aP_2;
  const char *aPreparingDevic;
  const char *aPreparingData;
  const char *aPresets;
  const char *aPressSaveToA_1;
  const char *anonymous_13;
  const char *aPriming;
  const char *aProtein;
  const char *aPodActivated;
  const char *aChangePodNow;
  const char *aPodExp_0;
  const char *aPodHasPassedEx;
  const char *aPodAlarm_0;
  const char *aPiB_B_B;
  const char *aPodStatusNotAv;
  const char *aResume;
  const char *aPmB_B_B;
  const char *a1Reading;
  const char *aDReadings;
  const char *aBasal;
  const char *aBg_0;
  const char *aBolus;
  const char *aCarb;
  const char *aProgramReminde;
  const char *aPdmLock;
  const char *aReminderSSched;
  const char *aRaB_B_B;
  const char *aRbB_B_B;
  const char *aPdmAlarm;
  const char *aClockReset;
  const char *aRmS;
  const char *aMmB_B_B;
  const char *aPdmOptions;
  const char *aSn08ld;
  const char *aRename;
  const char *aResetPdm;
  const char *anonymous_14;
  const char *aReviewAllSetti;
  const char *aReverseCorrect;
  const char *aScreenTimeOut;
  const char *aSec;
  const char *aSegment;
  const char *aSeptember;
  const char *aServingSize;
  const char *aSettings_0;
  const char *aSnacks;
  const char *aMealIobWillRed;
  const char *aCorrectionIobW;
  const char *aIobIsSubtracte;
  const char *aBgSound;
  const char *aPYRemains;
  const char *aUYRemains_0;
  const char *aPodExp;
  const char *aPodExpChangePo;
  const char *aUYRemains;
  const char *aExtBolus;
  const char *aStandardBgTags;
  const char *aSuggestedBol_1;
  const char *aSuspendBegin;
  const char *aSuspendCancel;
  const char *aSuspendInsulin;
  const char *aSuspend;
  const char *aSystemSetup;
  const char *aTag_0;
  const char *aC_1;
  const char *aTargetBgRange;
  const char *aTargetBg;
  const char *aTemp;
  const char *aTempBasalB;
  const char *aTempBasalPrese;
  const char *aTempBasal;
  const char *aTempUP;
  const char *aTime;
  const char *aTime_0;
  const char *aDateTimeChange;
  const char *aTimeRemaining;
  const char *aToday;
  const char *aToday_0;
  const char *aTotal;
  const char *aBasal_1;
  const char *anonymous_15;
  const char *aTotalDaily;
  const char *aTotalIob;
  const char *aTotal_0;
  const char *aType;
  const char *aUHr;
  const char *aU_3;
  const char *aUnits_1;
  const char *aUseForBolusCal;
  const char *aMyInfo;
  const char *aUserSettings;
  const char *aVibrate;
  const char *aVibrateThenBee;
  const char *aVibration;
  const char *aViewFoodLibrar;
  const char *aView;
  const char *aVolumeRemainin;
  const char *aYourExtendedBo;
  const char *aYourTempBasalW;
  const char *aYourTempBasalA;
  const char *aMmDdYy;
  const char *aDdMmYy;
  const char *aMm_dd_yy;
  const char *aDd_mm_yy;
  const char *aYyMmDd;
  const char *a1_2U0_25UHr3_5;
  const char *a12U025UHr35Hr;
  const char *aNotForHumanUse;
  const char *aCalibrationC_0;
  const char *aWhite;
  const char *aOrange;
  const char *aGreen;
  const char *aPurple;
  const char *aBlue;
  const char *aIdScreen;
  const char *aId;
  const char *aScreenColor;
  const char *aPressConfirmIf;
  const char *aLotLLu;
  const char *aTidTLu;
  const char *aThisWillTemp_0;
  const char *aThisWillTemp_1;
  const char *aThisWillTempor;
  const char *aEnglish;
  const char *aFrancais;
  const char *aDeutsch;
  const char *aNederlands;
  const char *aSvenska;
  const char *aItaliano;
  const char *aNorsk;
};

/* 20 */
struct struct_GPIO
{
  _DWORD DDIR;
  _DWORD OCR1;
  _DWORD OCR2;
  _DWORD ICONFA1;
  _DWORD ICONFA2;
  _DWORD ICONFB1;
  _DWORD ICONFB2;
  _DWORD DR;
  _DWORD GIUS;
  _DWORD SSR;
  _DWORD ICR1;
  _DWORD ICR2;
  _DWORD IMR;
  _DWORD ISR;
  _DWORD GPR;
  _DWORD SWR;
  _DWORD PUEN;
};

/* 22 */
struct struct_v4
{
  _DWORD dword0;
  _DWORD dword4;
  _DWORD dword8;
  _DWORD dwordC;
};

/* 23 */
struct __attribute__((packed)) __attribute__((aligned(2))) struct_a3_28
{
  _DWORD dword0;
  _BYTE byte4;
  _BYTE byte5;
  _BYTE gap6[2];
  _DWORD dword8;
  _BYTE gapC[4];
  _WORD word10;
};

/* 24 */
struct __attribute__((packed)) __attribute__((aligned(1))) struct_a1
{
  _DWORD dword0;
  _DWORD fun4;
  _DWORD word8;
  _DWORD dword0B;
  _DWORD dword10;
  _DWORD dword14;
  _DWORD dword18;
  _DWORD dword1B;
};

/* 25 */
struct __attribute__((aligned(2))) struct_record_info
{
  int field_0;
  char lenght;
  char field_5;
  char field_6;
  char field_7;
  char field_8;
  unsigned __int8 field_9;
  char field_A;
  char field_B;
};

/* 26 */
struct struct_bytes3
{
  int field_0;
  int field_4;
  _BYTE *field_8;
};

/* 29 */
struct struc_36h
{
  __int16 field_0;
  __int16 field_2;
  __int16 field_4;
  __int16 field_6;
  __int16 field_8;
  __int16 field_A;
  __int16 field_C;
  __int16 field_E;
  __int16 field_10;
  __int16 field_12;
  __int16 field_14;
  __int16 field_16;
  __int16 field_18;
  __int16 field_1A;
  __int16 field_1C;
  __int16 field_1E;
  __int16 field_20;
  __int16 field_22;
  __int16 field_24;
  __int16 field_26;
  __int16 field_28;
  __int16 field_2A;
  __int16 field_2C;
  __int16 field_2E;
  __int16 field_30;
  __int16 field_32;
  __int16 field_34;
};

/* 30 */
struct struct_msgs
{
  void *anonymous_0;
  void *aNoActivePod_Would;
  void *aBolusCanceled_UDe;
  void *aDeliveringUBolus;
  void *aInsulinDeliverySu;
  void *aUserInterfaceDi_0;
  void *aUserInterfaceDisa;
  void *aInsulinOnBoa_0;
  void *aSerialDiagnost;
  void *aRfCommunicatio;
  void *aEnterBolusAmou;
  void *aAnExtendedBolu;
  void *aPressConfirmTo;
  void *aYourOldExtende;
  void *aStartBolus;
  void *aTotalBolusUEnte;
  void *aExtendedBolusUE;
  void *aScheduleABgRemi;
  void *aRemindMeToCheck;
  void *aMaximumDuration;
  void *aEnterCurrentBg_;
  void *aAreYouGoingToEa;
  void *aCheckForKetones;
  void *aSelectARecentBg;
  void *aNoBgReadingsInT;
  void *aConfigureTheLis;
  void *aInvalidCustomTa;
  void *aSaveBgReading;
  void *aCarbPresets_1;
  void *anonymous_1;
  void *aSelectTag;
  void *aInvalidCarbPre;
  void *aEnterCarbs_;
  void *aEnterFiber_;
  void *aEnterFat_;
  void *aEnterProtein_;
  void *aEnterCalories_;
  void *aS_3;
  void *aDeletePreset;
  void *anonymous_2;
  void *aCarbs_0;
  void *aSuggestedBolusU;
  void *aPressOkToConfi;
  void *aNoBolusWillBeDe;
  void *aWarningExceedsM;
  void *aATempBasalIsCur;
  void *aEnterTempBasalR;
  void *aEnterDurationFo;
  void *aEnterDuration_0;
  void *aStartTempBasal;
  void *aStartTempBasalT;
  void *aStartTempBasalI;
  void *aStartTempBasalD;
  void *aRequestedTempBa;
  void *aEnterTempBasalC;
  void *aInsulinTotals;
  void *aBolusHistory;
  void *aBasalHistory;
  void *aLastStatusTDWou;
  void *aAlarmHistory;
  void *aCarbHistory_0;
  void *aAllHistory_0;
  void *aBg_1;
  void *aFoodLibrary;
  void *aFoodLibrarySS;
  void *aEnterTheFirstL;
  void *aFoodLibraryZ;
  void *aPressConfirm_0;
  void *aPodDeactivat_0;
  void *aCommunicationEr;
  void *aFillANewPodWit;
  void *aPrepareInfusion;
  void *aPrepareInfusi_0;
  void *aPressStartToIn;
  void *aPodIsActive_SHa;
  void *aPdmAndPodNotCom;
  void *aPdmAndPodNotC_0;
  void *aPodSetupWasNotC;
  void *aThePodChangePro;
  void *aPressDiscardToD;
  void *aBasalPrograms_0;
  void *aCannotEnableNew;
  void *aPressEnableToSt;
  void *aPodSuspended_SW;
  void *aS_5;
  void *aPressDeleteToRe;
  void *aEnterStartTimeF;
  void *aStartTimeTEnter;
  void *aSegmentTTEnterB;
  void *aEditName_;
  void *aInvalidBasalPro;
  void *aPressSaveToUpda;
  void *aYouHaveCreatedM;
  void *aPressSaveToAddS;
  void *aSEnterBasalRate;
  void *aCannotDeleteThe;
  void *aCannotEditActiv;
  void *aCannotCreateMor;
  void *aTempBasalPreset;
  void *aCannotEditAnAct;
  void *aSRateUDurationR;
  void *aSChangePDuratio;
  void *aPressDeleteTo_0;
  void *aPressDeleteTo_1;
  void *aInvalidTempBasa;
  void *aEnterRateForS_;
  void *aEnterDuration_1;
  void *aEnterDuration_2;
  void *aEnterChangeForS;
  void *aBolusPresets_0;
  void *aInvalidBolusPre;
  void *aEnterBolusPrese;
  void *aSAmountU;
  void *aPressDeleteTo_2;
  void *aCannotChangeTim;
  void *aBgSound_0;
  void *aVibrationOption;
  void *aPressSaveToUp_0;
  void *aBgGoalUpperLimi;
  void *aBgGoal_0;
  void *aEnterCurrentTim;
  void *aEnterCurrentYea;
  void *aEnterCurrentMon;
  void *aEnterCurrentDay;
  void *aDateFormat;
  void *aSelectTheWayNum;
  void *aPressConfirmToA;
  void *aPressConfirmT_0;
  void *aEnterMaximumBol;
  void *aMaxBolusConflic;
  void *aEnterMaximumBas;
  void *aMaxBasalRateCon;
  void *aSelectBolusIncr;
  void *aBolusCalculatio;
  void *aNotifyWhenPodEx;
  void *aNotifyWhenReser;
  void *aAlertIfNoPodSta;
  void *aBgReminder_0;
  void *aProgramReminder;
  void *aConfidenceRemin;
  void *aBolusReminder_0;
  void *aEnterStartTim_0;
  void *aYouHaveCreate_0;
  void *aBolusReminderTT;
  void *aPressDeleteTo_3;
  void *aPressSaveToUp_1;
  void *aSuspendInsulinD;
  void *aSuspendAllDeliv;
  void *aCancelExtendedB;
  void *aCancelTempBasal;
  void *aCancelTempBas_0;
  void *aInsulinDelivery;
  void *aPdmLock_0;
  void *aScreenTimeOut_0;
  void *aBacklightTimeOu;
  void *aPressOkToCheckA;
  void *aPressOkToChec_0;
  void *aPressConfirmToR;
  void *aCannotResetPdmW;
  void *aCheckingAlarms_;
  void *aLowPdmBatteries;
  void *aCannotCheckAlar;
  void *aSelectALanguage;
  void *aWelcomeToTheMyl;
  void *aWelcomeToTheOmn;
  void *aPressSaveToAcce;
  void *aYourMylifeOmnip;
  void *aYourOmnipodInsu;
  void *aTempBasal_0;
  void *aBgUnits_0;
  void *aEnterLowerLimit;
  void *aEnterUpperLimit;
  void *aSuggestedBolusC;
  void *aEnterTargetBgTh;
  void *aTargetCorrectAb;
  void *aEnterStartTim_1;
  void *anonymous_3;
  void *aSegmentTTEnterY;
  void *aYouHaveCreate_1;
  void *aPressSaveToAc_0;
  void *aSegmentTTTarget;
  void *aTargetBgBSugges;
  void *aEnterIcRatioTh;
  void *aInsulinToCarbI;
  void *aEnterStartTi_0;
  void *aSegmentTTEnterI;
  void *aPressSaveToAc_1;
  void *aEnterCorrection;
  void *aCorrectionFacto;
  void *aEnterStartTim_2;
  void *aSegmentTTEnter;
  void *aPressSaveToAc_2;
  void *aReverseCorre_1;
  void *aEnterDurationOf;
  void *aMissedBolusR_0;
  void *aExtendedBolus;
  void *aEnterMinimumBg;
  void *aCommunication_1;
  void *aCommunicatio_5;
  void *aCommunicatio_1;
  void *aCommunicationT;
  void *aCommunicatio_2;
  void *aCommunicatio_3;
  void *aCommunicationS;
  void *aCommunicationE;
  void *anonymous_4;
  void *aExtendedBolusI;
  void *anonymous_5;
  void *anonymous_6;
  void *aEnterAmountOfM;
  void *aExtendedBolu_0;
  void *aBolusCalcsCann;
  void *aCustomRemind_0;
  void *aInvalidCustomR;
  void *aEnterTime_;
  void *aSelectOption;
  void *aSTimeTSettingF;
  void *aPressDeleteToR;
  void *aEnterCode_;
  void *aApplyABloodSam;
  #27 (*anonymous_7)[];
  void *aSelectBgTag;
  void *aBgTagListIsEmp;
  void *aMeterErrorD_Se;
  void *aBolusCalcula_0;
  void *aBolusCalculati;
  void *aTreatYourLow_0;
  void *aDueToARecentCl;
  void *aBgCalibrationC;
  void *aTreatYourLowBg;
  void *aIfYouChooseToU;
  void *aControlSolutio;
  void *aMeterTempera_0;
  void *aDeleteCustomTa;
  void *aPodError_Insul;
  void *aPdmError_Rem_0;
  void *aPdmError_Remov;
  void *aOcclusionDet_0;
  void *aEmptyReservoir;
  void *aAutoOff_Remove;
  void *aPodExpired_Ins;
  void *aEndOfInsulinSu;
  void *aLowReservoir_R;
  void *aAutoOffAdvisor;
  void *aPodExpirationA;
  void *anonymous_8;
  void *aOcclusionDetec;
  void *aStuckKeyDetect;
  void *aStuckKeyDete_0;
  void *aLowPdmBatterie;
  void *aReminderCheckB;
  void *aReminderMissed;
  void *aCustomReminder;
  void *aReminderNoActi;
  void *aExpirationAler;
  void *aSystemError_Re;
  void *aSystemError__0;
  void *aPdmError_Press;
  void *aWarningClockRe;
  void *aPodDeactivatio;
  void *aPdmError_Memor;
  void *aLowPdmBatter_0;
  void *aUsbDeviceDetec;
  void *aUsbDeviceReady;
  #27 (*anonymous_9)[];
  #27 (*anonymous_10)[];
  #27 (*anonymous_11)[];
  #27 (*anonymous_12)[];
  #27 (*anonymous_13)[];
  #27 (*anonymous_14)[];
  #27 (*anonymous_15)[];
  #27 (*anonymous_16)[];
  #27 (*anonymous_17)[];
  #27 (*anonymous_18)[];
  #27 (*anonymous_19)[];
  #27 (*anonymous_20)[];
  #27 (*anonymous_21)[];
  #27 (*anonymous_22)[];
  #27 (*anonymous_23)[];
  #27 (*anonymous_24)[];
  #27 (*anonymous_25)[];
  #27 (*anonymous_26)[];
  #27 (*anonymous_27)[];
  void *aPressClearToRe;
  void *aClearingPdm_Do;
  void *aEnterYourNameO;
  void *aChooseAColorFo;
  void *aPdmId;
};

/* 31 */
struct struct_usb_sysreg
{
  _DWORD USB_CORE_HWMODE;
  _DWORD USB_CORE_CINTSTAT;
  _DWORD USB_CORE_CINTSTEN;
  _DWORD USB_CORE_CLKCTRL;
  _DWORD USB_CORE_RSTCTRL;
  _DWORD USB_CORE_FRAME_INVTL;
  _DWORD USB_CORE_FRAME_REMAIN;
  _DWORD USB_CORE_HNPCTRL;
  _DWORD USB_CORE_HNP_TMR1;
  _DWORD USB_CORE_HNP_TMR2;
  _DWORD USB_CORE_HNP_TMR3PCR;
  _DWORD USB_CORE_HNP_INTSTAT;
  _DWORD USB_CORE_HNP_INTEN;
  _DWORD USB_CORE_PAD[3];
  _DWORD USB_FUNC_FUNCOMSTAT;
  _DWORD USB_FUNC_DEVADDR;
  _DWORD USB_FUNC_SINTSTAT;
  _DWORD USB_FUNC_SINTEN;
  _DWORD USB_FUNC_XBUFINTSTAT;
  _DWORD USB_FUNC_YBUFINTSTAT;
  _DWORD USB_FUNC_XYINTEN;
  _DWORD USB_FUNC_XFILLSTAT;
  _DWORD USB_FUNC_YFILLSTAT;
  _DWORD USB_FUNC_EPEN;
  _DWORD USB_FUNC_EPRDY;
  _DWORD USB_FUNC_IMMDONEINT;
  _DWORD USB_FUNC_EPDONESTAT;
  _DWORD USB_FUNC_EPDONEEN;
  _DWORD USB_FUNC_EPTOGGBITS;
  _DWORD USB_FUNC_FRAME_NUMBER;
  _DWORD USB_HOST_HOSTCTRL;
  _DWORD USB_HOST_RESERVED_84;
  _DWORD USB_HOST_SINTSTAT;
  _DWORD USB_HOST_SINTEN;
  _DWORD USB_HOST_RESERVED_90;
  _DWORD USB_HOST_RESERVED_94;
  _DWORD USB_HOST_XBUFINTSTAT;
  _DWORD USB_HOST_YBUFINTSTAT;
  _DWORD USB_HOST_XYINTEN;
  _DWORD USB_HOST_RESERVED_A4;
  _DWORD USB_HOST_XFILLSTAT;
  _DWORD USB_HOST_YFILLSTAT;
  _DWORD USB_HOST_RESERVED_B0;
  _DWORD USB_HOST_RESERVED_B4;
  _DWORD USB_HOST_RESERVED_B8;
  _DWORD USB_HOST_RESERVED_BC;
  _DWORD USB_HOST_ETDENSET;
  _DWORD USB_HOST_ETDENCLR;
  _DWORD USB_HOST_RESERVED_C8;
  _DWORD USB_HOST_IMMDONEINT;
  _DWORD USB_HOST_ETDDONESTAT;
  _DWORD USB_HOST_ETDDONEEN;
  _DWORD USB_HOST_RESERVED_D8;
  _DWORD USB_HOST_RESERVED_DC;
  _DWORD USB_HOST_FRAME_NUMBER;
  _DWORD USB_HOST_FRAME_LSTHD;
  _DWORD USB_HOST_ROOTHUB_A;
  _DWORD USB_HOST_ROOTHUB_B;
  _DWORD USB_HOST_ROOTHUB_STATUS;
  _DWORD USB_HOST_ROOTHUB_PORTSTAT[3];
  _BYTE USB_TRANS_VENDORID0;
  _BYTE USB_TRANS_VENDORID1;
  _BYTE USB_TRANS_PRODUCTID0;
  _BYTE USB_TRANS_PRODUCTID1;
  _BYTE USB_TRANS_MODECTRL0_SET;
  _BYTE USB_TRANS_MODECTRL0_CLR;
  _BYTE USB_TRANS_OTGCTRL_SET;
  _BYTE USB_TRANS_OTGCTRL_CLR;
  _BYTE USB_TRANS_INTSOURCE;
  _BYTE USB_TRANS_RESERVED0;
  _BYTE USB_TRANS_INTLATCH_SET;
  _BYTE USB_TRANS_INTLATCH_CLR;
  _BYTE USB_TRANS_INTMASK_FSET;
  _BYTE USB_TRANS_INTMASK_FCLR;
  _BYTE USB_TRANS_INTMASK_TSET;
  _BYTE USB_TRANS_INTMASK_TCLR;
  _BYTE USB_TRANS_OTGSTATUS;
  _BYTE USB_TRANS_RESERVED2;
  _BYTE USB_TRANS_MODECTRL1_SET;
  _BYTE USB_TRANS_MODECTRL1_CLR;
  _BYTE USB_TRANS_BCDDEV0;
  _BYTE USB_TRANS_BCDDEV1;
  _BYTE USB_TRANS_RESERVED3;
  _BYTE USB_TRANS_RESERVED4;
  _BYTE USB_TRANS_OTGDEVADDR;
  _BYTE USB_TRANS_SEQOPS;
  _BYTE USB_TRANS_SEQRDSTRTADDR;
  _BYTE USB_TRANS_OPCTRL;
  _BYTE USB_TRANS_RESERVED5;
  _BYTE USB_TRANS_RESERVED6;
  _BYTE USB_TRANS_SCLK2SCLDIV;
  _BYTE USB_TRANS_INTCTRL;
  _DWORD USB_TRANS_PAD[54];
  _DWORD USB_SIMU_HC_CONTROL_HEAD_ED;
  _DWORD USB_SIMU_HC_BULK_HEAD_ED;
  _DWORD USB_ETD_MEM[128];
  _DWORD USB_EP_MEM[128];
  _DWORD USB_CTRL[64];
  _DWORD USB_OTG_RESERVED_700[64];
  _DWORD USB_DMA_REVISION;
  _DWORD USB_DMA_INTERRUPT_STATUS;
  _DWORD USB_DMA_INTERRUPT_ENABLE;
  _DWORD USB_ETD_DMA_ERROR_STATUS;
  _DWORD USB_EP_DMA_ERROR_STATUS;
  _DWORD USB_DMA_RESERVED_814[3];
  _DWORD USB_ETD_DMA_ENABLE;
  _DWORD USB_EP_DMA_ENABLE;
  _DWORD USB_ETD_DMA_ENABLE_X_TRIGER_REQUEST;
  _DWORD USB_EP_DMA_ENABLE_X_TRIGER_REQUEST;
  _DWORD USB_ETD_DMA_ENABLE_XY_TRIGER_REQUEST;
  _DWORD USB_EP_DMA_ENABLE_XY_TRIGER_REQUEST;
  _DWORD USB_ETD_DMA_BURST_4_ENABLE;
  _DWORD USB_EP_DMA_BURST_4_ENABLE;
  _DWORD USB_DMA_MISCELLANEOUS_CONTROL;
  _DWORD USB_DMA_RESERVED_844;
  _DWORD USB_ETD_DMA_CHANNEL_CLEAR;
  _DWORD USB_EP_DMA_CHANNEL_CLEAR;
  _DWORD USB_DMA_RESERVED_850[44];
  _DWORD USB_DMA_ETD_SYS_MEM_STRT_ADDR[32];
  _DWORD USB_DMA_EP_SYS_MEM_STRT_ADDR[32];
  _DWORD USB_ETD_DMA_BUF_XFER_PTR[32];
  _DWORD USB_EP_DMA_BUF_XFER_PTR[32];
  _DWORD USB_OTG_RESERVED[320];
  _BYTE USB_DATA_MEM[4096];
};

/* 32 */
struct USB_TRANS
{
  _BYTE USB_TRANS_VENDORID0;
  _BYTE USB_TRANS_VENDORID1;
  _BYTE USB_TRANS_PRODUCTID0;
  _BYTE USB_TRANS_PRODUCTID1;
  _BYTE USB_TRANS_MODECTRL0_SET;
  _BYTE USB_TRANS_MODECTRL0_CLR;
  _BYTE USB_TRANS_OTGCTRL_SET;
  _BYTE USB_TRANS_OTGCTRL_CLR;
  _BYTE USB_TRANS_INTSOURCE;
  _BYTE USB_TRANS_RESERVED0;
  _BYTE USB_TRANS_INTLATCH_SET;
  _BYTE USB_TRANS_INTLATCH_CLR;
  _BYTE USB_TRANS_INTMASK_FSET;
  _BYTE USB_TRANS_INTMASK_FCLR;
  _BYTE USB_TRANS_INTMASK_TSET;
  _BYTE USB_TRANS_INTMASK_TCLR;
  _BYTE USB_TRANS_OTGSTATUS;
  _BYTE USB_TRANS_RESERVED2;
  _BYTE USB_TRANS_MODECTRL1_SET;
  _BYTE USB_TRANS_MODECTRL1_CLR;
  _BYTE USB_TRANS_BCDDEV0;
  _BYTE USB_TRANS_BCDDEV1;
  _BYTE USB_TRANS_RESERVED3;
  _BYTE USB_TRANS_RESERVED4;
  _BYTE USB_TRANS_OTGDEVADDR;
  _BYTE USB_TRANS_SEQOPS;
  _BYTE USB_TRANS_SEQRDSTRTADDR;
  _BYTE USB_TRANS_OPCTRL;
  _BYTE USB_TRANS_RESERVED5;
  _BYTE USB_TRANS_RESERVED6;
  _BYTE USB_TRANS_SCLK2SCLDIV;
  _BYTE USB_TRANS_INTCTRL;
  _DWORD USB_TRANS_PAD[54];
};

/* 33 */
struct struct_usb_callX
{
  int field_0;
  _BYTE gap4[16];
  int field_20;
  _BYTE gap18[4];
  int field_28;
};

/* 34 */
struct struct_usb_callX2
{
  int field_0;
  _BYTE gap4[24];
  int field_28;
  _BYTE gap20[4];
  int field_36;
  int field_40;
};

